// Seed script - run once to populate the database with initial customer data
// Usage: DATABASE_URL=postgres://... node seed.js

const { Pool } = require('pg');
const bcrypt = require('bcryptjs');

const pool = new Pool({
    connectionString: process.env.DATABASE_URL,
    ssl: process.env.NODE_ENV === 'production' ? { rejectUnauthorized: false } : false
});

const customers = [
    // --- Göteborg centrum ---
    { name: "ICA Nära Heden", city: "Göteborg", address: "Sten Sturegatan 16", phone: "031 814070", email: "kundkontakt.heden@nara.ica.se", revenue: 28000000 },
    { name: "ICA Nära Haga", city: "Göteborg", address: "Pilgatan 20", phone: "031 130065", email: "joakim.x.kjellgren@nara.ica.se", revenue: 0 },
    { name: "ICA Focus", city: "Göteborg", address: "Åvägen 42", phone: "031 7030500", email: "kundkontakt@icafocus.se", revenue: 292000000 },
    { name: "ICA Supermarket Olskroken", city: "Göteborg", address: "Redbergsvägen 14", phone: "0722 067869", email: "kundkontakt.olskroken@supermarket.ica.se", revenue: 159000000 },
    { name: "ICA Nära Lunden", city: "Göteborg", address: "S:t Pauligatan 42", phone: "031 191100", email: "kundkontakt.lunden.goteborg@nara.ica.se", revenue: 0 },
    { name: "ICA Nära Kvillebäcken", city: "Göteborg", address: "Borstbindaregatan 12 A", phone: "031 170950", email: "daniel.x.sparrfelt@nara.ica.se", revenue: 0 },
    { name: "ICA Nära Linnégatan", city: "Göteborg", address: "Linnégatan 41", phone: "031 3875180", email: "bjorn.lundh@nara.ica.se", revenue: 0 },
    { name: "ICA Kvantum Sannegården", city: "Göteborg", address: "Vintergatan 4", phone: "031 7794040", email: "kundkontakt.sannegarden@kvantum.ica.se", revenue: 322000000 },
    { name: "ICA Supermarket Majorna", city: "Göteborg", address: "Karl Johansgatan 21", phone: "031 141713", email: "kontor.majorna@supermarket.ica.se", revenue: 102000000 },
    { name: "ICA Kvantum Munkebäck", city: "Göteborg", address: "Lilla Munkebäcksgatan 2 A", phone: "031 7556700", email: "helen.collins@kvantum.ica.se", revenue: 483000000 },
    { name: "ICA Nära Träffen", city: "Göteborg", address: "Björcksgatan 53", phone: "031 254572", email: "farhads.gholamreza@nara.ica.se", revenue: 0 },
    { name: "Maxi ICA Stormarknad Göteborg", city: "Göteborg", address: "Grafiska Vägen 16", phone: "031 7466100", email: "kundkontakt.goteborg@maxi.ica.se", revenue: 679000000 },
    { name: "ICA Nära Effkå", city: "Göteborg", address: "Kungsladugårdsg 15", phone: "031 149485", email: "therese.kanterdickson@nara.ica.se", revenue: 0 },
    { name: "ICA Nära Toppen", city: "Göteborg", address: "Kungsladugårdsgatan 104", phone: "031 148688", email: "lemai.quach@nara.ica.se", revenue: 0 },
    { name: "ICA Nära Stabbetorget", city: "Göteborg", address: "Stabbetorget 1", phone: "031 251218", email: "rebecca.jonsson@nara.ica.se", revenue: 0 },
    { name: "ICA Kvantum Frölunda", city: "Västra Frölunda", address: "Radiovägen 5", phone: "031 477800", email: "kundkontakt.vastrafrolunda@kvantum.ica.se", revenue: 214000000 },
    { name: "ICA Supermarket Frölunda", city: "Västra Frölunda", address: "Smyckegatan 1", phone: "0736 318512", email: "charlotte.ohlsson@supermarket.ica.se", revenue: 37609000 },
    { name: "ICA Nära Fiskebäck", city: "Västra Frölunda", address: "Mungårdsgatan 21", phone: "031 290028", email: "thomas.renstrom@nara.ica.se", revenue: 0 },
    { name: "ICA Supermarket Åkeredshallen", city: "Västra Frölunda", address: "Spektrumsgatan 1", phone: "031 280801", email: "kontakt.akeredshallen@supermarket.ica.se", revenue: 75000000 },
    { name: "Maxi ICA Stormarknad Högsbo", city: "Västra Frölunda", address: "Lona Knapes gata 1", phone: "031 7127100", email: "kundkontakt.hogsbo@maxi.ica.se", revenue: 783000000 },
    { name: "ICA Nära Nya Varvet", city: "Västra Frölunda", address: "Starbåtsgatan 1", phone: "031 297401", email: "magnus.korle@nara.ica.se", revenue: 0 },
    { name: "ICA Kvantum Bäckebol", city: "Hisings Backa", address: "Transportgatan 19-21", phone: "031 880688", email: "jorgen.kjerstensson@kvantum.ica.se", revenue: 160000000 },
    { name: "ICA Supermarket Brunnsbo", city: "Hisings Backa", address: "Brunnsbotorget 3", phone: "031 506580", email: "kenta.l.bratt@supermarket.ica.se", revenue: 57000000 },
    { name: "Maxi ICA Stormarknad Angered", city: "Angered", address: "Angered Centrum", phone: "031 3325600", email: "kundkontakt.angered@maxi.ica.se", revenue: 297000000 },
    { name: "ICA Supermarket Gårdsten", city: "Angered", address: "Muskotgatan 5", phone: "031 3332750", email: "kontor.gardsten@supermarket.ica.se", revenue: 44000000 },
    { name: "ICA Supermarket Hjällbo", city: "Angered", address: "Hjällbo Centrum", phone: "031 460130", email: "alma.draganovic@supermarket.ica.se", revenue: 44000000 },
    { name: "Maxi ICA Stormarknad Torslanda", city: "Torslanda", address: "Gamla Flygplatsvägen 60", phone: "031 7205600", email: "kundkontakt.torslanda@maxi.ica.se", revenue: 455000000 },
    { name: "ICA Nära Björlanda", city: "Torslanda", address: "Linas Lycka 2", phone: "031 925295", email: "marie.backman@nara.ica.se", revenue: 0 },
    { name: "ICA City Centrum", city: "Borås", address: "Allégatan 21", phone: "033 444300", email: "centrum@citybutikerna.se", revenue: 0 },
    { name: "ICA City Knalleland", city: "Borås", address: "Skaraborgsvägen 25", phone: "033 447700", email: "knalleland@citybutikerna.se", revenue: 0 },
    { name: "Maxi ICA Stormarknad Borås", city: "Borås", address: "Trandögatan 16", phone: "033 211800", email: "kundkontakt.boras@maxi.ica.se", revenue: 699000000 },
    { name: "ICA Supermarket Knalleland", city: "Borås", address: "Bergslenagatan 7", phone: "033 211300", email: "mikael.carlsson@supermarket.ica.se", revenue: 83000000 },
    { name: "ICA Supermarket Byttorp", city: "Borås", address: "Vindelgatan 45", phone: "033 413811", email: "christoffer.x.jonsson@supermarket.ica.se", revenue: 83875000 },
    { name: "ICA Nära Hulta", city: "Borås", address: "Trallingsgatan 1", phone: "033 3484340", email: "gabriel.bjorkman@nara.ica.se", revenue: 0 },
    { name: "ICA Nära Pilen", city: "Borås", address: "Guldbrandsgatan 12", phone: "033 156300", email: "joakim.olsson@nara.ica.se", revenue: 0 },
    { name: "ICA City Brämhult", city: "Brämhult", address: "Brämhults Torg", phone: "033 230600", email: "bramhult@citybutikerna.se", revenue: 0 },
    { name: "ICA Nära Hjärtat", city: "Gånghester", address: "Stora Vägen 2", phone: "033 256056", email: "patric.malm@nara.ica.se", revenue: 0 },
    { name: "ICA Supermarket Köpet", city: "Sandared", address: "Boråsvägen 3", phone: "033 255019", email: "oskar.farjhage@supermarket.ica.se", revenue: 85000000 },
    { name: "ICA City Fristad", city: "Fristad", address: "Fristadstorget 10", phone: "033 210400", email: "fristad@citybutikerna.se", revenue: 0 },
    { name: "ICA Nära Hedared", city: "Hedared", address: "Vemmenhultsvägen 2", phone: "033 242020", email: "emelie.samuelsson@nara.ica.se", revenue: 0 },
    { name: "ICA Supermarket Matmor", city: "Trollhättan", address: "Kungsgatan 30", phone: "0520 12550", email: "info@matmor.se", revenue: 76877000 },
    { name: "ICA Kvantum Jätten", city: "Trollhättan", address: "Skogmansgatan 22", phone: "0520 405000", email: "fredrik.nyqvist@kvantum.ica.se", revenue: 266000000 },
    { name: "ICA Supermarket Sylte", city: "Trollhättan", address: "Sylte Center", phone: "0520 470580", email: "thomas.svensson@supermarket.ica.se", revenue: 62629000 },
    { name: "Maxi ICA Stormarknad Trollhättan", city: "Trollhättan", address: "Överby Köpcentrum", phone: "0520 488300", email: "kundkontakt.trollhattan@maxi.ica.se", revenue: 372000000 },
    { name: "ICA Nära Kryddlunds", city: "Trollhättan", address: "Slätternavägen 1", phone: "0520 424012", email: "kenneth.manvik@nara.ica.se", revenue: 0 },
    { name: "ICA Supermarket Spara", city: "Uddevalla", address: "Odengatan 3", phone: "0522 653939", email: "arthur.hansson@supermarket.ica.se", revenue: 174418000 },
    { name: "ICA Kvantum Uddevalla", city: "Uddevalla", address: "Göteborgsvägen 18", phone: "0522 645464", email: "kundkontakt.uddevalla@kvantum.ica.se", revenue: 171000000 },
    { name: "ICA Nära Dalaberg", city: "Uddevalla", address: "Lövskogsgatan 8", phone: "0522 70945", email: "christopher.karlberg@nara.ica.se", revenue: 0 },
    { name: "ICA Maxi Uddevalla", city: "Uddevalla", address: "Torp Köpcentrum", phone: "0522 653700", email: "kundkontakt.torp@kvantum.ica.se", revenue: 447000000 },
    { name: "ICA Supermarket Ljungskile", city: "Ljungskile", address: "Vällebergsvägen 27", phone: "0522 261230", email: "kundkontakt.ljungskile@supermarket.ica.se", revenue: 126000000 },
    { name: "ICA Nära Norrmalm", city: "Skövde", address: "Gustav Adolfs gata 6", phone: "0500 415656", email: "magnus.friberg@nara.ica.se", revenue: 0 },
    { name: "ICA Kvantum Skövde", city: "Skövde", address: "G:a Kungsvägen 54", phone: "0500 478830", email: "urban.andersson@kvantum.ica.se", revenue: 218000000 },
    { name: "Maxi ICA Stormarknad Skövde", city: "Skövde", address: "Köpmannagatan 3", phone: "0500 445300", email: "kundkontakt.skovde@maxi.ica.se", revenue: 406000000 },
    { name: "ICA Nära Skultorp", city: "Skövde", address: "Klagstorpsvägen 6", phone: "0500 433038", email: "dejan.vulevic@nara.ica.se", revenue: 0 },
    { name: "ICA Nära Blomman", city: "Skövde", address: "Hästskovägen 6", phone: "0500 461650", email: "linus.kaminsky@nara.ica.se", revenue: 0 },
    { name: "ICA Supermarket Tibro", city: "Tibro", address: "Alletorget 8", phone: "0504 787800", email: "annelie.magnusson@supermarket.ica.se", revenue: 157000000 },
    { name: "ICA Nära City Livs", city: "Tibro", address: "Storgatan 10", phone: "0504 20209", email: "kalle.johansson@nara.ica.se", revenue: 0 },
    { name: "ICA Kvantum Tidaholm", city: "Tidaholm", address: "Järnvägsgatan 5", phone: "0502 18800", email: "sverker.josefsson@kvantum.ica.se", revenue: 185000000 },
    { name: "ICA Supermarket Hjo", city: "Hjo", address: "Vasagatan 1", phone: "0503 13020", email: "christer.larsson@supermarket.ica.se", revenue: 145000000 },
    { name: "ICA Nära Tidan", city: "Tidan", address: "Vårlundavägen 5", phone: "", email: "", revenue: 0 },
    { name: "ICA Nära Timmersdala", city: "Timmersdala", address: "Mariestadsvägen 15", phone: "0511 81001", email: "peter.lindholm@nara.ica.se", revenue: 0 },
    { name: "ICA Supermarket Falköping", city: "Falköping", address: "Falegatan 11A", phone: "0515 776470", email: "daniel.gustafsson@supermarket.ica.se", revenue: 99000000 },
    { name: "Maxi ICA Stormarknad Falköping", city: "Falköping", address: "Lönnerbladsgatan 2", phone: "0515 776440", email: "kundkontakt.falkoping@maxi.ica.se", revenue: 310000000 },
    { name: "ICA Matfocus Slutarp", city: "Kinnarp", address: "Samuels gränd 1", phone: "0515 33119", email: "anna.skoglund@nara.ica.se", revenue: 0 },
    { name: "ICA Nära Floby", city: "Floby", address: "Köpmangatan 2", phone: "0515 40550", email: "hakan.persson@nara.ica.se", revenue: 0 },
    { name: "ICA Nära Evaldssons", city: "Åsarp", address: "Centrumvägen 33", phone: "0515 50015", email: "fredric.evaldsson@nara.ica.se", revenue: 0 },
    { name: "ICA Kvantum Vänersborg", city: "Vänersborg", address: "Brogatan 4", phone: "0521 260610", email: "anders.blomster@kvantum.ica.se", revenue: 229000000 },
    { name: "ICA Supermarket Älgen", city: "Vargön", address: "Storegårdsvägen 4", phone: "0521 224906", email: "christoffer.russo@supermarket.ica.se", revenue: 68000000 },
    { name: "ICA Nära Cypressen", city: "Brålanda", address: "Storgatan 21", phone: "0521 30028", email: "carina.karlsson@nara.ica.se", revenue: 0 },
    { name: "ICA Kvantum Hjertberg", city: "Lidköping", address: "Framnäsvägen 1", phone: "0510 82000", email: "anders.fredriksson@kvantum.ica.se", revenue: 475000000 },
    { name: "ICA Nära Klockan", city: "Lidköping", address: "Rådagatan 31", phone: "0510 60375", email: "per-arne.dahl@nara.ica.se", revenue: 0 },
    { name: "ICA Supermarket Margretelund", city: "Lidköping", address: "Floragatan 8", phone: "0510 485850", email: "maria.lexberg@supermarket.ica.se", revenue: 88000000 },
    { name: "ICA Nära Vinninga", city: "Vinninga", address: "Varavägen 2", phone: "0510 50006", email: "", revenue: 0 },
    { name: "ICA Kvantum Götene", city: "Götene", address: "Lidköpingsv 9", phone: "0511 345700", email: "johan.olofson@kvantum.ica.se", revenue: 199000000 },
    { name: "ICA Kvantum Munken", city: "Skara", address: "Skaraborgsgatan 28", phone: "0511 342300", email: "jonas.skara@kvantum.ica.se", revenue: 0 },
    { name: "ICA Kvantum Vara", city: "Vara", address: "Torggatan 48", phone: "0512 797050", email: "klas.peterson@kvantum.ica.se", revenue: 173000000 },
    { name: "ICA Supermarket Grästorp", city: "Grästorp", address: "Torggatan 12", phone: "0514 10081", email: "ulrika.litzell@supermarket.ica.se", revenue: 73000000 },
    { name: "ICA Nära Sahlins", city: "Kvänum", address: "Järnvägsgatan 5", phone: "0512 92010", email: "lars-olof.sahlin@nara.ica.se", revenue: 0 },
    { name: "ICA Nära Karl-Åkes Storköp", city: "Stora Levene", address: "Storgatan 20", phone: "0512 797770", email: "sara.karlsson@nara.ica.se", revenue: 0 },
    { name: "ICA Nära Axvall", city: "Axvall", address: "Bangatan 5", phone: "0511 62620", email: "oskar.x.skalstad@nara.ica.se", revenue: 0 },
    { name: "ICA Nära BK-Hallen", city: "Vedum", address: "Larvsvägen 5", phone: "0512 40061", email: "anna.nilsson@nara.ica.se", revenue: 0 },
    { name: "ICA Nära Åkanten", city: "Alingsås", address: "Stationsgatan 30", phone: "0322 665530", email: "karin.persson@nara.ica.se", revenue: 0 },
    { name: "Maxi ICA Stormarknad Alingsås", city: "Alingsås", address: "Hemvägen 19", phone: "0322 78400", email: "kundkontakt.alingsas@maxi.ica.se", revenue: 634000000 },
    { name: "ICA Supermarket Noltorp", city: "Alingsås", address: "Noltorps Centrum", phone: "0322 665569", email: "hakan.x.engstrom@supermarket.ica.se", revenue: 69451000 },
    { name: "ICA Nära Stadsskogen", city: "Alingsås", address: "Rubingatan 1", phone: "0322 285810", email: "jaana.frobose@nara.ica.se", revenue: 0 },
    { name: "ICA Nära Gabrielssons", city: "Vårgårda", address: "Ljurhalla", phone: "", email: "", revenue: 0 },
    { name: "ICA Supermarket Sollebrunn", city: "Sollebrunn", address: "Trollhättevägen 6", phone: "0322 83730", email: "marcus.brunnhage@supermarket.ica.se", revenue: 82860000 },
    { name: "ICA Supermarket Nossebro", city: "Nossebro", address: "Sturegatan 9", phone: "0512 50016", email: "christer.kjall@supermarket.ica.se", revenue: 0 },
    { name: "ICA Nära Ljung", city: "Ljung", address: "Stationsvägen 14", phone: "0513 50119", email: "emma.mackay@nara.ica.se", revenue: 0 },
    { name: "ICA Supermarket Herrljunga", city: "Herrljunga", address: "Magasinsgatan 6", phone: "0513 22270", email: "peter.andersson@supermarket.ica.se", revenue: 53000000 },
    { name: "Maxi ICA Stormarknad Kungälv", city: "Kungälv", address: "Gymnasiegatan 8", phone: "0303 15000", email: "Kundkontakt.kungalv@maxi.ica.se", revenue: 0 },
    { name: "ICA Nära Skafferiet", city: "Kungälv", address: "Ivar Claessonsgatan 34", phone: "076 6973975", email: "robin.x.granqvist@nara.ica.se", revenue: 0 },
    { name: "ICA Nära Kode", city: "Kode", address: "Kodevägen 11-13", phone: "0303 51650", email: "arnold.eriksson@nara.ica.se", revenue: 0 },
    { name: "ICA Kvantum Mölndal", city: "Mölndal", address: "Barnhemsgatan 22", phone: "031 7872700", email: "magnus.alkmark@kvantum.ica.se", revenue: 225000000 },
    { name: "ICA Nära Rävekärr", city: "Mölndal", address: "Fågelbergsgatan 2", phone: "031 277575", email: "kent.pettersson@nara.ica.se", revenue: 0 },
    { name: "ICA Nära Pedagogen Park", city: "Mölndal", address: "Kunskapsgatan 8", phone: "031 3824329", email: "mikael.ferm@nara.ica.se", revenue: 0 },
    { name: "ICA Supermarket Lindome", city: "Lindome", address: "Almåsgången 1", phone: "031 997170", email: "linda.dahlin@supermarket.ica.se", revenue: 77000000 },
    { name: "ICA Kvantum Mariestad", city: "Mariestad", address: "Viktoriagatan 20", phone: "0501 278000", email: "info@oxen.nu", revenue: 263000000 },
    { name: "ICA Nära Lyrestad", city: "Lyrestad", address: "Järnvägsgatan 1", phone: "0501 50027", email: "pontus.berlin@nara.ica.se", revenue: 0 },
    { name: "ICA Supermarket Töreboda", city: "Töreboda", address: "Drottninggatan 2", phone: "0506 19200", email: "jan.2.andersson@supermarket.ica.se", revenue: 110000000 },
    { name: "ICA Supermarket Riddaren", city: "Hova", address: "Torggatan 10", phone: "0506 30001", email: "johan.hellstrom@supermarket.ica.se", revenue: 65000000 },
    { name: "ICA Supermarket Gullspång", city: "Gullspång", address: "Storgatan 26", phone: "0551 20003", email: "peter.gullspang@supermarket.ica.se", revenue: 70554000 },
    { name: "ICA Nära Hallsås", city: "Lerum", address: "Kring-alles väg 52", phone: "0302 10203", email: "martin.zettergren@nara.ica.se", revenue: 0 },
    { name: "ICA Supermarket Servett", city: "Lerum", address: "Almekärrsvägen 1", phone: "0302 694310", email: "magnus.johansson@supermarket.ica.se", revenue: 73198000 },
    { name: "ICA Kvantum Lerum", city: "Lerum", address: "Hulans Torg 1", phone: "0302 522700", email: "kundkontakt.lerum@kvantum.ica.se", revenue: 555000000 },
    { name: "ICA Supermarket Floda", city: "Floda", address: "Rurik Holms väg 8-10", phone: "0302 35900", email: "daniel.wennroth@supermarket.ica.se", revenue: 104000000 },
    { name: "Maxi ICA Stormarknad Partille", city: "Partille", address: "Parallellvägen 1", phone: "031 3400500", email: "kundkontakt.partille@maxi.ica.se", revenue: 415000000 },
    { name: "ICA Supermarket Prima", city: "Sävedalen", address: "Skolvägen 7", phone: "031 3408780", email: "marie.alexandersson@supermarket.ica.se", revenue: 97854000 },
    { name: "ICA Supermarket Vallhamra", city: "Sävedalen", address: "Vallhamra Torg 1B", phone: "031 3408830", email: "kundkontakt.vallhamra@supermarket.ica.se", revenue: 102292000 },
    { name: "ICA Kvantum Stenungsund", city: "Stenungsund", address: "Vassgatan 1", phone: "0303 726200", email: "robert.larsson@kvantum.ica.se", revenue: 241000000 },
    { name: "ICA Supermarket Stenungsund", city: "Stenungsund", address: "Uppegårdsvägen 2", phone: "0303 727080", email: "svante.karlsson@supermarket.ica.se", revenue: 71000000 },
    { name: "ICA Nära Jörlanda", city: "Jörlanda", address: "Ranehedsvägen 2", phone: "0303 52035", email: "linda.karlsson@nara.ica.se", revenue: 0 },
    { name: "ICA Nära Strömstad", city: "Strömstad", address: "S:a Hamngatan 8", phone: "0526 14400", email: "niclas.x.strandell@nara.ica.se", revenue: 0 },
    { name: "ICA Kvantum Strömstad", city: "Strömstad", address: "Prästängsvägen 2", phone: "0526 717400", email: "simon.hansson@kvantum.ica.se", revenue: 246000000 },
    { name: "ICA Nära Sydkoster", city: "Sydkoster", address: "Torget 2", phone: "0526 20035", email: "kundkontakt.sydkoster@nara.ica.se", revenue: 0 },
    { name: "ICA Supermarket Hedemyrs", city: "Tanumshede", address: "Affärsvägen 12", phone: "0525 29140", email: "jacob.bengtsson@supermarket.ica.se", revenue: 156863000 },
    { name: "ICA Nära Grebbestad", city: "Grebbestad", address: "Hamnplan", phone: "0733 213199", email: "magnus.berglund@nara.ica.se", revenue: 0 },
    { name: "ICA Nära Östads Livs", city: "Bullaren", address: "Byvägen 1", phone: "0525 50022", email: "par.andersson@nara.ica.se", revenue: 0 },
    { name: "ICA Supermarket Skutan", city: "Hamburgsund", address: "Skutan 1", phone: "0525 64800", email: "lars.gunnarsson@supermarket.ica.se", revenue: 86000000 },
    { name: "ICA Kvantum Kungsbacka", city: "Kungsbacka", address: "Varlagård 16", phone: "0300 51150", email: "erika.lindberg@kvantum.ica.se", revenue: 279000000 },
    { name: "Maxi ICA Stormarknad Kungsbacka", city: "Kungsbacka", address: "Hedebrovägen 50", phone: "0300 33600", email: "info.kungsbacka@maxi.ica.se", revenue: 615000000 },
    { name: "ICA Supermarket Vallda", city: "Vallda", address: "Egnahemsvägen 7", phone: "0300 25444", email: "anders.fureh@supermarket.ica.se", revenue: 89044000 },
    { name: "ICA Supermarket Åsa", city: "Åsa", address: "Åsa Stationsväg 13", phone: "0340 656010", email: "anna.lowstrom@supermarket.ica.se", revenue: 100000000 },
    { name: "ICA Kvantum Varberg", city: "Varberg", address: "Torggatan 26", phone: "0340 666700", email: "ica.varberg@kvantum.ica.se", revenue: 291000000 },
    { name: "ICA Nära NG:s Snabbköp", city: "Varberg", address: "Magasinsgatan 64", phone: "", email: "", revenue: 0 },
    { name: "ICA Hajen Lågpris", city: "Varberg", address: "Monarkvägen 2", phone: "", email: "", revenue: 0 },
    { name: "ICA Nära Matboden", city: "Varberg", address: "Lindbergsvägen 18", phone: "", email: "", revenue: 0 },
    { name: "ICA Supermarket Tvååker", city: "Tvååker", address: "Alvägen 5", phone: "0340 40030", email: "daniel.tornblad@supermarket.ica.se", revenue: 84132000 },
    { name: "ICA Nära Rolfstorp", city: "Rolfstorp", address: "Toers väg 1", phone: "", email: "", revenue: 0 },
    { name: "ICA Supermarket Derome", city: "Veddige", address: "Bjurumsvägen 1", phone: "0340 31100", email: "marie.romell@supermarket.ica.se", revenue: 64199000 },
    { name: "ICA Nära Bua", city: "Bua", address: "Värö Center", phone: "", email: "", revenue: 0 },
    { name: "ICA Nära Zachrisson", city: "Väröbacka", address: "Varbergsvägen 2", phone: "", email: "", revenue: 0 },
    { name: "ICA Kvantum Landvetter", city: "Landvetter", address: "Brattåstorget 3", phone: "031 977070", email: "kundkontakt.landvetter@kvantum.ica.se", revenue: 295000000 },
    { name: "ICA Nära Mölnlycke", city: "Mölnlycke", address: "Lövskogsvägen 1", phone: "031 886288", email: "johan.heden@nara.ica.se", revenue: 0 },
    { name: "ICA Nära Djupedalsäng", city: "Mölnlycke", address: "Råstensvägen 1", phone: "031 881151", email: "ulf.svensson@nara.ica.se", revenue: 0 },
    { name: "ICA Nära Hindås", city: "Hindås", address: "Hindås Stationsväg 43", phone: "0301 10015", email: "jonas.malmros@nara.ica.se", revenue: 0 },
    { name: "ICA Nära Horred", city: "Horred", address: "Varbergsvägen 436", phone: "0320 18010", email: "markus.jernberg@nara.ica.se", revenue: 0 },
    { name: "ICA Kvantum MM - Skene", city: "Skene", address: "Klevagårdsgatan 3", phone: "0320 30630", email: "martin.ivarson@kvantum.ica.se", revenue: 249000000 },
    { name: "ICA Nära Hyssna", city: "Hyssna", address: "Göteborgsvägen 102", phone: "0320 38040", email: "emelie.carlsson@nara.ica.se", revenue: 0 },
    { name: "ICA Nära Fritsla", city: "Fritsla", address: "Kommunalhusvägen 4", phone: "0320 70047", email: "henrik.x.johansson@nara.ica.se", revenue: 0 },
    { name: "ICA Supermarket Lysekil", city: "Lysekil", address: "Landsvägsgatan 17", phone: "0523 665590", email: "albert.pettersson@supermarket.ica.se", revenue: 108000000 },
    { name: "ICA Nära Grundsund", city: "Grundsund", address: "Lönndalsvägen 45", phone: "0523 21105", email: "anders.widen@nara.ica.se", revenue: 0 },
    { name: "ICA Nära Brastad", city: "Brastad", address: "Hallindenvägen 16", phone: "0523 40134", email: "caroline.wessberg@nara.ica.se", revenue: 0 },
    { name: "ICA Svenssons Livs Alvhem", city: "Alvhem", address: "Adolf Fredriks väg 14", phone: "0303 336003", email: "carina.mortensen@nara.ica.se", revenue: 0 },
    { name: "ICA Supermarket Älvängen", city: "Älvängen", address: "Svensktorpsvägen 15", phone: "0303 700710", email: "info.alvangen@supermarket.ica.se", revenue: 75000000 },
    { name: "ICA Kvantum Ale", city: "Nödinge", address: "Ale Torg 7", phone: "0303 97500", email: "mikael.sagstrom@kvantum.ica.se", revenue: 0 },
    { name: "ICA Supermarket Pärlan", city: "Henån", address: "Hamntorget", phone: "0304 32770", email: "pernilla.olofsson@supermarket.ica.se", revenue: 138678000 },
    { name: "ICA Supermarket Varekilsboden", city: "Varekil", address: "Hedströms väg 1", phone: "0304 10158", email: "stephan.berntsson@supermarket.ica.se", revenue: 88140000 },
    { name: "ICA Supermarket Kållekärr", city: "Kållekärr", address: "Kållekärr 50", phone: "0304 660026", email: "johan.olsson@supermarket.ica.se", revenue: 86891000 },
    { name: "ICA Nära Höviksnäs", city: "Höviksnäs", address: "Höviksnäsvägen 2", phone: "0304 661630", email: "camilla.busck@nara.ica.se", revenue: 0 },
    { name: "ICA Supermarket Nordeviks", city: "Skärhamn", address: "Kroksdalsvägen 4", phone: "0304 676900", email: "anders.nordevik@supermarket.ica.se", revenue: 218000000 },
    { name: "ICA Nära Rorsman", city: "Rönnäng", address: "Allévägen 5", phone: "0304 672001", email: "karolina.werinius@nara.ica.se", revenue: 0 },
    { name: "ICA Nära Dyröboden", city: "Dyrön", address: "Hamnvägen 46", phone: "072 2315750", email: "butik.dyroboden@nara.ica.se", revenue: 0 },
    { name: "ICA Nära Munkedalshallen", city: "Munkedal", address: "Stationsvägen 2", phone: "0524 10366", email: "erik.svedmark@nara.ica.se", revenue: 0 },
    { name: "ICA Nära Dingle", city: "Dingle", address: "Järnvägsgatan 4", phone: "0524 18970", email: "rickard.olsson@nara.ica.se", revenue: 0 },
    { name: "ICA Nära Arwidssons", city: "Hällevadsholm", address: "Norra Bohusvägen 1", phone: "0524 50001", email: "alexander.nilsson@nara.ica.se", revenue: 0 },
    { name: "ICA Supermarket Skeppet", city: "Kungshamn", address: "Skeppartorget", phone: "0523 666040", email: "maria.jarleklint@supermarket.ica.se", revenue: 102868000 },
    { name: "ICA Nära Ankaret", city: "Smögen", address: "Hasselösundsvägen", phone: "0523 30500", email: "emma.wetzo@nara.ica.se", revenue: 0 },
    { name: "ICA Supermarket Boström", city: "Lilla Edet", address: "Göteborgsvägen 49", phone: "0520 473550", email: "patrik.johansson@supermarket.ica.se", revenue: 190866000 },
    { name: "ICA Nära Matkassen Lödöse", city: "Lödöse", address: "Centrum", phone: "0520 660010", email: "lars.hansson@nara.ica.se", revenue: 0 },
    { name: "ICA Supermarket Kronan", city: "Mellerud", address: "Landsvägsgatan 53", phone: "0530 10633", email: "micke.andersson@supermarket.ica.se", revenue: 54777000 },
    { name: "ICA Nära Grinstads Lanthandel", city: "Grinstad", address: "Grinstad", phone: "0530 50050", email: "anko.boskma@nara.ica.se", revenue: 0 },
    { name: "ICA Supermarket Bengtsfors", city: "Bengtsfors", address: "Centrumvägen 10", phone: "0531 10338", email: "johan.cardell@supermarket.ica.se", revenue: 87000000 },
    { name: "ICA Nära Billingsfors", city: "Billingsfors", address: "Stenebyvägen 13", phone: "0531 30030", email: "william.cander@nara.ica.se", revenue: 0 },
    { name: "ICA Nära Optimisten", city: "Gustavsfors", address: "Årjängsvägen 31", phone: "0531 20001", email: "kundkontakt.gustavsfors@nara.ica.se", revenue: 0 },
    { name: "ICA Supermarket Lejonet", city: "Åmål", address: "Mellanbrogatan 10", phone: "0532 608660", email: "susanne.enell@supermarket.ica.se", revenue: 124000000 },
    { name: "ICA Kvantum Svenljunga", city: "Svenljunga", address: "Kinnagatan 3", phone: "0325 619880", email: "rasmus.bynander@kvantum.ica.se", revenue: 180000000 },
    { name: "ICA Nära Monicanders", city: "Mjöbäck", address: "Öxabäcksvägen 7", phone: "0325 34004", email: "jonas.enoksson@nara.ica.se", revenue: 0 },
    { name: "ICA Kvantum Tranemo", city: "Tranemo", address: "Storgatan 32", phone: "0325 70480", email: "peter.hallen@kvantum.ica.se", revenue: 126000000 },
    { name: "ICA Nära Mathyttan", city: "Limmared", address: "Torget", phone: "0325 71024", email: "rasmus.rosengren@nara.ica.se", revenue: 0 },
    { name: "ICA Nära Länghem", city: "Länghem", address: "Boråsvägen 26", phone: "0325 40021", email: "taghi.rashti@nara.ica.se", revenue: 0 },
    { name: "ICA Nära Dalstorp", city: "Dalstorp", address: "Ulricehamnsvägen 15", phone: "0321 60037", email: "marcus.alexandersson@nara.ica.se", revenue: 0 },
    { name: "ICA Supermarket Tornet", city: "Ulricehamn", address: "Strandgatan 6", phone: "0321 26610", email: "calle.bergman@supermarket.ica.se", revenue: 143000000 },
    { name: "Maxi ICA Stormarknad Ulricehamn", city: "Ulricehamn", address: "Ubbarpsvägen 2A", phone: "0321 534600", email: "", revenue: 270000000 },
    { name: "ICA Nära Timmele", city: "Timmele", address: "Ängstigen 4", phone: "0321 30176", email: "jakob.flygare@nara.ica.se", revenue: 0 },
    { name: "ICA Nära Gällstad", city: "Gällstad", address: "Boråsvägen 40", phone: "0321 70001", email: "johan.gustafsson@nara.ica.se", revenue: 0 },
    { name: "ICA Supermarket Färgelanda", city: "Färgelanda", address: "Centrumvägen 7", phone: "0528 10565", email: "daniel.f.larsson@supermarket.ica.se", revenue: 76000000 },
    { name: "ICA Supermarket Karlsborg", city: "Karlsborg", address: "Storgatan 18", phone: "0505 17400", email: "helen.lundqvist@supermarket.ica.se", revenue: 117000000 },
    { name: "ICA Nära Fredéns", city: "Mölltorp", address: "Centralgatan 20", phone: "0505 30017", email: "urban.freden@nara.ica.se", revenue: 0 },
    { name: "ICA Nära Lanthandeln Undenäs", city: "Undenäs", address: "Svanhultsvägen 3", phone: "0505 20475", email: "lanthandeln.undenas@nara.ica.se", revenue: 0 },
    { name: "ICA Nära Bollebygd", city: "Bollebygd", address: "Gästgifvaretorget 1", phone: "033 285050", email: "andreas.x.hartvigsson@nara.ica.se", revenue: 0 },
    { name: "ICA Nära Alexius Livs", city: "Öckerö", address: "Hårdebacksvägen 2", phone: "031 965734", email: "erina.tillander@nara.ica.se", revenue: 0 },
    { name: "ICA Supermarket Hönö", city: "Hönö", address: "Lökholmsvägen 2", phone: "031 976790", email: "hakan.jarnebratt@supermarket.ica.se", revenue: 0 },
    { name: "ICA Nära Björkö", city: "Öckerö", address: "Bohus-Björkö", phone: "031 961022", email: "erik.almhojd@nara.ica.se", revenue: 0 },
    { name: "ICA Nära Rörö Strandkassa", city: "Rörö", address: "Sörikringsvägen 16", phone: "031 964008", email: "susannem.johansson@nara.ica.se", revenue: 0 },
];

async function seed() {
    console.log('Seeding database...');

    // Check if already seeded
    const { rows } = await pool.query('SELECT COUNT(*) FROM customers');
    if (parseInt(rows[0].count) > 0) {
        console.log(`Database already has ${rows[0].count} customers. Skipping seed.`);
        process.exit(0);
    }

    for (const c of customers) {
        await pool.query(
            'INSERT INTO customers (name,city,address,status,comment,revenue,contacted_by,phone,email) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)',
            [c.name, c.city || '', c.address || '', 'Prospekt', '', c.revenue || 0, '', c.phone || '', c.email || '']
        );
    }

    // Seed Hemköp Torpa as first client
    await pool.query(
        'INSERT INTO clients (name,city,address,contact_person,phone,email,revenue,start_date,comment) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)',
        ['Hemköp Torpa', 'Vänersborg', 'Torpavägen 2', '', '', '', 0, '2026-03-01', 'Första kunden!']
    );

    console.log(`Seeded ${customers.length} customers and 1 client.`);
    process.exit(0);
}

seed().catch(err => { console.error(err); process.exit(1); });
